## Below are related to Catalog file
CATALOG_FILE_NAME = "Catalog.xlsx"
CATALOG_DATAFRAME_NAME = "Catalog"

CATALOG_PRODUCT_NAME = "Product"
CATALOG_UNIT_PRICE = "Price"

CATALOG_CRITICAL_COLUMNS = [CATALOG_PRODUCT_NAME, CATALOG_UNIT_PRICE]

CATALOG_DROP_COLUMNS = [CATALOG_UNIT_PRICE]