## Below are related to Catalog file
CATALOG_FILE_NAME = "Catalog.xlsx"
CATALOG_PRODUCT_NAME = "Product Name"
CATALOG_DESCRIPTION = "DESCRIPTION"
CATALOG_UNIT_PRICE = "UNIT FOB PRICE"

CATALOG_HEADERS = [CATALOG_PRODUCT_NAME, CATALOG_DESCRIPTION, CATALOG_UNIT_PRICE]
