## Below are related to Enquiry file
ENQUIRY_FILE_NAME = 'Enquiry.xlsx'
ENQUIRY_DATAFRAME_NAME = "Enquiry"

ENQUIRY_PRODUCT_NAME = "Product"
ENQUIRY_QUANTITY = "Quantity"

ENQUIRY_DEFAULT_QUANTITY = 1

ENQUIRY_CRITICAL_COLUMNS = [ENQUIRY_PRODUCT_NAME, ENQUIRY_QUANTITY]