## Below are related to Pricetag file
PRICETAG_FILE_NAME = "Pricetag.xlsx"
PRICETAG_PRODUCT_NAME = "Product Name"
PRICETAG_DESCRIPTION = "DESCRIPTION"
PRICETAG_UNIT_PRICE = "UNIT FOB PRICE"

PRICETAG_HEADERS = [PRICETAG_PRODUCT_NAME, PRICETAG_DESCRIPTION, PRICETAG_UNIT_PRICE]
